name: 'release'

on:
  push:
    branches:
    - 'master'

jobs:
  release:
    if: "startsWith(github.event.head_commit.message, 'Release: v')"
    name: 'Release'
    uses: 'google-github-actions/.github/.github/workflows/release.yml@v0'
